import type { PanchangData } from "@/lib/panchang/types";
import ChoghadiyaCard from "@/components/panchang/ChoghadiyaCard";

const labels = { vara: "वार", tithi: "तिथि", paksha: "पक्ष", nakshatra: "नक्षत्र", yoga: "योग", karana: "करण", sunrise: "सूर्योदय", sunset: "सूर्यास्त", moonrise: "चंद्रोदय", moonset: "चंद्रास्त", rahuKaal: "राहु काल", yamaganda: "यमगण्ड", gulika: "गुलिक काल", abhijitMuhurat: "अभिजीत मुहूर्त", brahmaMuhurat: "ब्रह्म मुहूर्त" } as const;
function time(value?: string) { if (!value) return "जानकारी उपलब्ध नहीं"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("hi-IN", { hour: "numeric", minute: "2-digit", hour12: true }).format(date); }
function range(value?: { start: string; end: string }) { return value ? `${time(value.start)} – ${time(value.end)}` : "जानकारी उपलब्ध नहीं"; }
function Cell({ label, value }: { label: string; value?: string }) { return <div className="rounded-xl border border-amber-100 bg-[#fffcf5] p-3"><dt className="text-xs font-bold tracking-wide text-[#9c6a3d]">{label}</dt><dd className="mt-1 font-semibold text-[#51230f]">{value ?? "जानकारी उपलब्ध नहीं"}</dd></div>; }

export default function PanchangDetails({ data }: { data: PanchangData }) {
  const limbs = [{ label: labels.vara, value: data.vara }, { label: labels.tithi, value: data.tithi?.name }, { label: labels.paksha, value: data.tithi?.paksha }, { label: labels.nakshatra, value: data.nakshatra?.name }, { label: labels.yoga, value: data.yoga?.name }, { label: labels.karana, value: data.karana?.name }];
  const dayPeriods = Object.entries(data.dayPeriods).map(([key, value]) => ({ label: labels[key as keyof typeof labels], value: range(value) }));
  const availableMuhurats = [{ label: labels.abhijitMuhurat, value: data.dayPeriods.abhijitMuhurat }, { label: labels.brahmaMuhurat, value: data.dayPeriods.brahmaMuhurat }].filter((item) => item.value);
  return <div className="grid gap-5"><section aria-labelledby="details-heading" className="rounded-3xl border border-[#ead6b9] bg-[#fffdf9] p-5 shadow-[0_14px_36px_rgba(94,52,18,0.09)]"><p className="text-xs font-bold tracking-[0.16em] text-[#a85e25]">चयनित तिथि का विवरण</p><h2 id="details-heading" className="mt-1 text-2xl font-bold text-[#51230f]">मुख्य पंचांग</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{limbs.map((item) => <Cell key={item.label} {...item} />)}</dl></section>
    <section aria-labelledby="sun-heading" className="rounded-3xl border border-[#ead6b9] bg-[#fffdf9] p-5 shadow-[0_14px_36px_rgba(94,52,18,0.09)]"><h2 id="sun-heading" className="text-2xl font-bold text-[#51230f]">सूर्य और चंद्र</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Cell label={labels.sunrise} value={time(data.sunrise)} /><Cell label={labels.sunset} value={time(data.sunset)} /><Cell label={labels.moonrise} value={time(data.moonrise)} /><Cell label={labels.moonset} value={time(data.moonset)} /></dl></section>
    {dayPeriods.length > 0 && <section aria-labelledby="periods-heading" className="rounded-3xl border border-[#ead6b9] bg-[#fffdf9] p-5 shadow-[0_14px_36px_rgba(94,52,18,0.09)]"><h2 id="periods-heading" className="text-2xl font-bold text-[#51230f]">समय</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{dayPeriods.map((item) => <Cell key={item.label} {...item} />)}</dl></section>}
    {availableMuhurats.length > 0 && <section aria-labelledby="muhurat-heading" className="rounded-3xl border border-[#ead6b9] bg-[#fffdf9] p-5 shadow-[0_14px_36px_rgba(94,52,18,0.09)]"><h2 id="muhurat-heading" className="text-2xl font-bold text-[#51230f]">शुभ मुहूर्त</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2">{availableMuhurats.map((item) => <Cell key={item.label} label={item.label} value={range(item.value)} />)}{data.muhurats.map((item) => <Cell key={`${item.title}-${item.start}`} label={item.title} value={range(item)} />)}</dl></section>}
    <ChoghadiyaCard day={data.choghadiya.day} night={data.choghadiya.night} />
  </div>;
}
