import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { pujaServices } from "@/data/puja-services";
import { generatePageMetadata } from "@/lib/seo";

export const metadata: Metadata = generatePageMetadata({ title: "पूजा एवं अनुष्ठान | उज्जैन", description: "उज्जैन से पारंपरिक पूजा, अनुष्ठान और ज्योतिषीय मार्गदर्शन की सेवाएँ, सामान्य प्रक्रिया तथा बुकिंग की जानकारी देखें।", path: "/puja-services", image: "/images/services/shiv-puja.png" });

export default function PujaServicesPage() {
  return <div className="bg-[#fff9f0] pb-16 lg:pb-24"><section className="relative isolate overflow-hidden bg-[#4b2413] px-5 py-16 text-center text-[#fff9ec] sm:px-8 sm:py-20 lg:px-12"><Image src="/images/services/shiv-puja.png" fill priority alt="" className="-z-20 object-cover opacity-20" sizes="100vw" /><div aria-hidden="true" className="absolute inset-0 -z-10 bg-[#4b2413]/85" /><div className="mx-auto max-w-3xl"><p className="inline-flex rounded-full border border-amber-100/30 bg-white/10 px-4 py-2 text-sm font-bold text-amber-100">उज्जैन, मध्य प्रदेश</p><h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-5xl">पूजा एवं अनुष्ठान</h1><p className="mt-5 text-lg leading-8 text-amber-50/90">पारंपरिक पूजा सेवाओं, उनकी प्रक्रिया और बुकिंग संबंधी जानकारी एक स्थान पर देखें।</p></div></section><main className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{pujaServices.map((service) => <Link key={service.id} href={`/puja-services/${service.id}`} className="group overflow-hidden rounded-3xl border border-[#ead6b9] bg-[#fffdf9] shadow-[0_12px_32px_rgba(94,52,18,0.09)] transition hover:-translate-y-1 hover:shadow-[0_18px_38px_rgba(94,52,18,0.16)] focus:outline-none focus:ring-2 focus:ring-[#a35420]"><div className="relative h-44"><Image src={service.image} alt={service.imageAlt} fill sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#3f1d0c]/65 to-transparent" /><span className="absolute bottom-4 left-5 text-2xl">{service.icon}</span></div><div className="p-6"><h2 className="text-xl font-bold text-[#51230f]">{service.title}</h2><p className="mt-3 text-sm leading-6 text-[#70401f]">{service.subtitle}</p><span className="mt-5 inline-block text-sm font-bold text-[#8b3516]">पूरी जानकारी देखें →</span></div></Link>)}</div></main></div>;
}
